server:
  port: 8080

spring:
  #데이터베이스 설정
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password:

  #JPA 설정
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddlAuto: create

  #라이브 리로드 설정
  devtools:
    livereload:
      enabled: true

  #타임리프 설정
  thymeleaf:
    cache: false
    prefix: file:src/main/resources/templates/

  #정적자원 설정(CSS, JS, 이미지)
  web:
    resources:
      staticLocations: file:src/main/resources/static/

  #파일 업로드 설정
  servlet:
    multipart:
      maxFileSize: 20MB #파일 한 개 최대 용량
      maxRequestSize: 60MB #전체파일 최대용량

# 파일 경로 설정
file:
  url: /upload/
  path: c:/uploads/

#로거 설정
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace